name: Deploy GitHub Pages

on:
  workflow_run:
    workflows: ["My First GitHub Actions"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
